version: '3.8'

services:
    todo-app:
        image: todo-app:${DOCKER_IMAGE_TAG:-latest}
        container_name: todo-app
        build: .
        ports:
            - 3000:3000
        environment:
            TODO_DB_FILE_ENV: 'development'
            DANCER_PORT: '3000'
            DANCER_ENVIRONMENT: 'development'
        init: true
        volumes:
            - "${PWD-.}:/usr/src/app"
